### ISSUE TITLE
Exponential Upgrades

### ISSUE THREAD

**Issue by TheJP** [TheJP/GreenGameJam2018#1]
Issue to collect all tasks and problems regarding upgrades and exponential growth.

# Tasks
- [ ] Wave monster count and strength grow exponentially
- [ ] Monsters drop give blood when killed
- [ ] Upgrade placeables using blood
- [ ] Upgrade system for each placeable that makes it exponentially stronger (and consume exponentially more)
- [ ] Adjust wave counts to player count
